# COMP90084 Workshop Week 7
In this week's workshop, we'll program the algorithms we encountered during the lectures last week.

In [1]:
import numpy as np

# Importing standard Qiskit libraries
from qiskit import QuantumCircuit, transpile, Aer, IBMQ, QuantumRegister, ClassicalRegister
import qiskit as qk
from qiskit.circuit import Gate
from qiskit.tools.jupyter import *
from qiskit.visualization import *
import matplotlib.pyplot as plt
from qiskit.quantum_info import partial_trace, DensityMatrix, Statevector
%matplotlib inline
# shots simulation
backend_sim = Aer.get_backend('qasm_simulator')
# statevector
backend_sv = Aer.get_backend('statevector_simulator')


In [2]:
I = np.identity(2)
print(I)
Z = np.matrix([[1, 0],[0, -1]])
X = np.matrix([[0, 1],[1, 0]])

Z1 = np.kron(Z,I)
X2 = np.kron(I, X)

print(Z1+X2)

print(np.kron(Z,X))



# # CNOT = 0.5 * (np.outer(I,I) + np.outer(Z,I) + np.outer(I,X) - np.outer(Z,X))
CNOT = 0.5 * (np.kron(I,I) + np.kron(Z,I) + np.kron(I,X) - np.kron(Z,X))


[[1. 0.]
 [0. 1.]]
[[ 1.  1.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  0. -1.  1.]
 [ 0.  0.  1. -1.]]
[[ 0  1  0  0]
 [ 1  0  0  0]
 [ 0  0  0 -1]
 [ 0  0 -1  0]]


In [3]:

I = np.identity(2)
print(I)
Z = np.matrix([[1, 0],[0, -1]])
X = np.matrix([[0, 1],[1, 0]])

# # CNOT = 0.5 * (np.outer(I,I) + np.outer(Z,I) + np.outer(I,X) - np.outer(Z,X))
CNOT = 0.5 * (np.kron(I,I) + np.kron(Z,I) + np.kron(I,X) - np.kron(Z,X))


print(CNOT)
print()


x = np.array([1,0,0,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,1,0,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,0,1,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,0,0,1])
print(x)
print(CNOT.dot(x))
print()




CNOT = 0.5 * (np.kron(I,I) + np.kron(I,Z) + np.kron(X,I) - np.kron(X,Z))


print(CNOT)
print()


x = np.array([1,0,0,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,1,0,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,0,1,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,0,0,1])
print(x)
print(CNOT.dot(x))
print()


[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

[1 0 0 0]
[[1. 0. 0. 0.]]

[0 1 0 0]
[[0. 1. 0. 0.]]

[0 0 1 0]
[[0. 0. 0. 1.]]

[0 0 0 1]
[[0. 0. 1. 0.]]

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

[1 0 0 0]
[[1. 0. 0. 0.]]

[0 1 0 0]
[[0. 0. 0. 1.]]

[0 0 1 0]
[[0. 0. 1. 0.]]

[0 0 0 1]
[[0. 1. 0. 0.]]



In [49]:
from math import sqrt

import array_to_latex as a2l

I = np.identity(2)
Z = np.matrix([[1, 0],[0, -1]])
X = np.matrix([[0, 1],[1, 0]])

I_L = np.identity(16)


X1_L = np.kron(np.kron(np.kron(X,I), X),I)
X2_L = np.kron(np.kron(np.kron(I,X), X),I)
Z1_L = np.kron(np.kron(np.kron(Z,I), I),Z)
Z2_L = np.kron(np.kron(np.kron(I,Z), I),Z)

ZX_L = np.kron(np.kron(np.kron(Z,X), X),Z)
XZ_L = np.kron(np.kron(np.kron(X,Z), X),Z)


# X1_L = np.kron(np.kron(np.kron(I,X), I),X)
# X2_L = np.kron(np.kron(np.kron(I,X), X),I)
# Z1_L = np.kron(np.kron(np.kron(Z,I), I),Z)
# Z2_L = np.kron(np.kron(np.kron(I,I), Z),I)

# ZX_L = np.kron(np.kron(np.kron(Z,X), X),Z)
# ZX_L = Z1_L * X2_L



def C(bit_str1, bit_str2):
    c = np.zeros(16)
    c[int(bit_str1, 2)] = 1/sqrt(2)
    c[int(bit_str2, 2)] = 1/sqrt(2)
    return c

L00 = C('0000', '1111')
L01 = C('0110', '1001')
L10 = C('1010', '0101')
L11 = C('1100', '0011')

def bra(x):
    return np.conj(np.transpose(x))

CNOT1_2_L = np.outer(L00,bra(L00)) + np.outer(L01,bra(L01)) + np.outer(L11,bra(L10)) + np.outer(L10,bra(L11))


# CNOT1_2_L_alt = np.round(0.5 * (I_L + Z1_L + X2_L - ZX_L), decimals=1)
CNOT1_2_L_alt = 0.5 * (I_L + Z1_L + X2_L - ZX_L)
CNOT2_1_L_alt = 0.5 * (I_L + Z2_L + X1_L - XZ_L)

print(CNOT1_2_L_alt)
print(np.round(0.5 * (I_L + Z1_L + X2_L - ZX_L), decimals=1))
# CNOT1_2_L_alt = np.round(0.5 * (I_L + Z1_L + X2_L), decimals=1)
# CNOT1_2_L_alt = np.round(0.5 * (I_L + Z2_L + X1_L), decimals=1)
# print(I_L)
# print(Z1_L)
# print(X1_L)
# print(X1)

# print( np.matmul(Z1_L,X2_L))
# print(np.round(CNOT1_2_L - CNOT1_2_L_alt, decimals=1))


# print(np.outer(L10,bra(L11)))
# recp_sqrt_2 = 1/sqrt(2)
CNOT1_2_L = CNOT1_2_L_alt

print(CNOT1_2_L_alt.dot(L10)==L11)



assert((CNOT1_2_L_alt.dot(L10) == L11).all())
assert((CNOT1_2_L_alt.dot(L11) == L10).all())
assert((CNOT1_2_L_alt.dot(L00) == L00).all())
assert((CNOT1_2_L_alt.dot(L01) == L01).all())


assert((CNOT2_1_L_alt.dot(L10) == L10).all())
assert((CNOT2_1_L_alt.dot(L11) == L01).all())
assert((CNOT2_1_L_alt.dot(L00) == L00).all())
assert((CNOT2_1_L_alt.dot(L01) == L11).all())

def lat_mat_name(name, mat):
    matStr = a2l.to_ltx(mat, print_out=False)
    return "$"+name+"="+matStr+"$"


print(lat_mat_name("I",I))
print(lat_mat_name("X",X))
print(lat_mat_name("Z",Z))


a2l.to_ltx(L00)
a2l.to_ltx(L01)
a2l.to_ltx(L10)
a2l.to_ltx(L11)




a2l.to_ltx(CNOT1_2_L_alt, frmt='{:1.0f}')
a2l.to_ltx(CNOT2_1_L_alt, frmt='{:1.0f}')








# x = L10
# print("L10")
# print(x)
# print(CNOT1_2_L.dot(x))
# print(L11)

# print("L11")
# x = L11
# print(x)
# print(CNOT1_2_L.dot(x))
# print(L10)

# print("L00")
# x = L00
# print(x)
# print(CNOT1_2_L.dot(x))
# print(L00)

# print("L01")
# x = L01
# print(x)
# print(CNOT1_2_L.dot(x))
# print(L01)





[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0

In [50]:

a2l.to_ltx(L00, row=False)
a2l.to_ltx(L01, row=False)
a2l.to_ltx(L10, row=False)
a2l.to_ltx(L11, row=False)

\begin{bmatrix}
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71
\end{bmatrix}
\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix}
\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix}
\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix}


## Q1.4

### Defining Pauli Matrices

$I=\begin{bmatrix}
  1.00 &  0.00\\
  0.00 &  1.00
\end{bmatrix}$
$X=\begin{bmatrix}
  0.00 &  1.00\\
  1.00 &  0.00
\end{bmatrix}$
$Z=\begin{bmatrix}
  1.00 &  0.00\\
  0.00 & -1.00
\end{bmatrix}$

### Defining Logical Pauli Operators

$\overline{I} = I \otimes I \otimes I \otimes I $

$\overline{X_1} = X_1 X_3 = X \otimes I \otimes X \otimes I $

$\overline{Z_1} = Z_1 X_4 = Z \otimes I \otimes I \otimes Z $

$\overline{X_2} = X_2 X_3 = I \otimes X \otimes X \otimes I $

$\overline{Z_2} = Z_2 Z_4 = I \otimes Z \otimes I \otimes Z $

$\overline{Z_1 \otimes X_2} = Z \otimes X \otimes X \otimes Z  $

$\overline{X_1 \otimes Z_2} = X \otimes Z \otimes X \otimes Z  $


<br/>

### Logical CNOT gates

$CNOT_{1,2} = 0.5( I + Z_1 + X_2 - Z_1 \otimes X_2) $
\
$=> \overline{CNOT_{1,2}} = 0.5( \overline{I} + \overline{Z_1} + \overline{X_2} - \overline{Z_1 \otimes X_2}) $
\
$= \begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}$


<br/>


$CNOT_{2,1} = 0.5( I + Z_2 + X_1 - X_1 \otimes Z_2) $
\
$=> \overline{CNOT_{2,1}} = 0.5( \overline{I} + \overline{Z_2} + \overline{X_1} - \overline{X_1 \otimes Z_2}) $
\
$=\begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}$


### Define Logical Basis

$\ket{00}_L = \frac{1}{\sqrt{2}}(\ket{0000} + \ket{1111}) = \begin{bmatrix} 0.71 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.71 \end{bmatrix}^T$

$\ket{01}_L = \frac{1}{\sqrt{2}}(\ket{0110} + \ket{1001}) = \begin{bmatrix}
  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.71 &  0.00 &  0.00 &  0.71 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00
\end{bmatrix}^T$

$\ket{10}_L = \frac{1}{\sqrt{2}}(\ket{1010} + \ket{0101}) = \begin{bmatrix}
  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.71 &  0.00 &  0.00 &  0.00 &  0.00 &  0.71 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00
\end{bmatrix}^T$

$\ket{11}_L = \frac{1}{\sqrt{2}}(\ket{1100} + \ket{0011}) = \begin{bmatrix}
  0.00 &  0.00 &  0.00 &  0.71 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.00 &  0.71 &  0.00 &  0.00 &  0.00
\end{bmatrix}^T$

### Proof that CNOT1,2 is correct

$\overline{CNOT_{1,2}} \ket{00}_L = \begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}\begin{bmatrix}
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71
\end{bmatrix}=\begin{bmatrix}
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71
\end{bmatrix} = \ket{00}_L
$





$\overline{CNOT_{1,2}} \ket{01}_L = \begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix}=\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix} = \ket{01}_L
$



$\overline{CNOT_{1,2}} \ket{10}_L = \begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix}=\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix} = \ket{11}_L
$



$\overline{CNOT_{1,2}} \ket{11}_L = \begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix}=\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix} = \ket{10}_L
$

### Proof that CNOT2,1 is correct

</br>

$\overline{CNOT_{2,1}} \ket{00}_L = \begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}\begin{bmatrix}
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71
\end{bmatrix}=\begin{bmatrix}
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71
\end{bmatrix} = \ket{00}_L
$




$\overline{CNOT_{2,1}} \ket{01}_L = \begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix}=\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix} = \ket{11}_L
$



$\overline{CNOT_{2,1}} \ket{10}_L = \begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}\begin{bmatrix}
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71
\end{bmatrix}=\begin{bmatrix}
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71
\end{bmatrix} = \ket{10}_L
$


$\overline{CNOT_{2,1}} \ket{11}_L = \begin{bmatrix}
  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0 \\
  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0 \\
  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0 \\
  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1  &  0  &  0 \\
  0  &  0  &  0  &  0  &  1  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0 \\
  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  0  &  1 
\end{bmatrix}\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix}=\begin{bmatrix}
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.71\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00\\
  0.00
\end{bmatrix} = \ket{01}_L
$


In [5]:
CNOT = 0.5 * (np.kron(I,I) + np.kron(Z,I) + np.kron(I,X) - np.kron(Z,X))


print(CNOT)
print()


x = np.array([1,0,0,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,1,0,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,0,1,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,0,0,1])
print(x)
print(CNOT.dot(x))
print()




CNOT = 0.5 * (np.kron(I,I) + np.kron(I,Z) + np.kron(X,I) - np.kron(X,Z))


print(CNOT)
print()


x = np.array([1,0,0,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,1,0,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,0,1,0])
print(x)
print(CNOT.dot(x))
print()

x = np.array([0,0,0,1])
print(x)
print(CNOT.dot(x))
print()


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

[1 0 0 0]
[[1. 0. 0. 0.]]

[0 1 0 0]
[[0. 1. 0. 0.]]

[0 0 1 0]
[[0. 0. 0. 1.]]

[0 0 0 1]
[[0. 0. 1. 0.]]

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

[1 0 0 0]
[[1. 0. 0. 0.]]

[0 1 0 0]
[[0. 0. 0. 1.]]

[0 0 1 0]
[[0. 0. 1. 0.]]

[0 0 0 1]
[[0. 1. 0. 0.]]

